name: PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  PR:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "24"
          check-latest: true
      - name: check java
        run: |
          java --version
          mvn --version
      - name: Publish to Github Packages
        timeout-minutes: 10
        run: mvn -B verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}